services:
  searxng:
    image: searxng/searxng:latest
    container_name: nexus-searxng

    ports:
      - "8080:8080"

    restart: unless-stopped

    environment:
      - BASE_URL=http://localhost:8080/

    # Mount local configuration into container
    volumes:
      #- searxng-data:/etc/searxng
      - ./config:/etc/searxng

#volumes:
#  searxng-data: