from typing import Any

from pydantic import BaseModel, Field


class ToolCall(BaseModel):
    """
    Structured tool call generated by the model.

    Example:
    {
        "tool": "calculator",
        "arguments": {
            "expression": "25 * 47"
        }
    }
    """

    tool: str = Field(
        description="Name of the tool to execute."
    )

    arguments: dict[str, Any] = Field(
        default_factory=dict,
        description="Arguments passed to the tool."
    )