import json
import re

from app.agent.tool_call import ToolCall


TOOL_CALL_PATTERN = re.compile(
    r"<tool_call>\s*(.*?)\s*</tool_call>",
    re.DOTALL,
)


def parse_tool_call(
    response: str,
) -> ToolCall | None:
    """
    Parse a tool call generated by the model.

    Example input:

    <tool_call>
    {
        "name": "calculator",
        "arguments": {
            "expression": "25 * 47"
        }
    }
    </tool_call>

    Returns:
        ToolCall if a tool call exists.

        None if no tool call is present.
    """

    match = TOOL_CALL_PATTERN.search(
        response
    )

    if match is None:
        return None

    try:
        payload = json.loads(
            match.group(1)
        )

    except json.JSONDecodeError as exc:
        raise ValueError(
            f"Invalid tool call JSON:\n{response}"
        ) from exc

    if "name" not in payload:
        raise ValueError(
            "Tool call missing 'name' field."
        )

    return ToolCall(
        tool=payload["name"],
        arguments=payload.get(
            "arguments",
            {},
        ),
    )